### PR TITLE
Beta Release

### LINKED ISSUE #6: Sign in/up flow should display errors to users
Currently, if any error happens, only developers can see those in the console output.

Instead, users should be informed if the sign up/sign in flow fails with reason.

### PR DESCRIPTION
**Pull request by anrattanasouk**
Fix #6

### CODE REVIEW

File: Fun GenUITests/Fun_GenUITests.swift [hunk 1]
```diff
@@ -10,43 +10,47 @@ import XCTest
...
-
+    
     override func tearDownWithError() throws {
         // Put teardown code here. This method is called after the invocation of each test method in the class.
     }
     
-    // UI test for frontend, adding an option on the VoteView page
-    func testAddOption() throws {
+    // UI test for activity creation
+    func testCreateActivity() throws {
```
Comment (ApolloZhu) [inline Fun GenUITests/Fun_GenUITests.swift:27]: It's okay to name the method whatever, as long as it starts with test

File: Shared/View/VoteView.swift [hunk 2]
```diff
@@ -8,51 +8,47 @@
...
+                Text("Loading...")
             }
+            
             Spacer()
             HStack {
                 Spacer()
-                NavigationLink(destination: TempHomeView()) {
-                    Text("Done")
-                }
+                Button(action: { self.presentationMode.wrappedValue.dismiss() }, label: {Text("Done")})
```
Comment (ApolloZhu) [inline Shared/View/VoteView.swift:51]: @finnj00 / @Joon333 could you please fix the style issue?

**Review by ApolloZhu — CHANGES_REQUESTED** [review]

File: Shared/View/AuthenticationView.swift [hunk 3]
```diff
@@ -65,13 +75,18 @@ struct SignUpView: View {
...
-                        // TODO: display error to user
-                        print(error)
+                        alertText = error.localizedDescription
+                        showingAlert = true
                     }
                 }
             } label: {
                 Text("Sign Up")
             }
+            .alert("Error signing up", isPresented: $showingAlert) {
```
Comment (ApolloZhu) [inline Shared/View/AuthenticationView.swift:85]: @elulu3 thanks for adding the error alerts to handle some of the errors! I tweaked them a little bit to show the more detailed error messages in addition to error titles, allowing us to display "user already exist", "incorrect email format", and etc.

**Review by ApolloZhu — APPROVED** [review]
